name: consul-dmitriis
version: "0.8.0"
summary: Consul is a tool for service discovery, monitoring and configuration
description: |
  Consul is distributed, highly available, and extremely scalable.
  Consul provides service discovery, health checking, key/value storage and
  multi-datacenter.
grade: stable
confinement: strict

apps:
  consul:
    command: consul-snap
    plugs: [network, network-bind, network-observe]
    slots: [consul-tmp]

slots:
  consul-tmp:
    interface: content
    content: consul-tmp
    # read-write access to the consul socket for
    # HTTP communication with the consul agent
    # write: [/tmp]
    write: [$SNAP_COMMON]
    # write: [$SNAP_DATA]
    # write: [$SNAP]

parts:
  consul:
    source: https://github.com/hashicorp/consul.git
    plugin: go
    go-importpath: github.com/hashicorp/consul
    source-tag: v0.8.0
    build-packages: [git]
  script:
    source: .
    plugin: dump
    snap: ["consul-snap"]
